apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: stateful-todo
spec:
  serviceName: "postgres"
  replicas: 1
  minReadySeconds: 10       # by default is 0
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17.2
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          livenessProbe:
            exec:
              command: [ "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
            failureThreshold: 10
            periodSeconds: 10
            timeoutSeconds: 45
          volumeMounts:
            - name: postgredb-volume
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          env:
            -  name: PGDATA
               value: /var/lib/postgresql/data/pgdata
            -  name: POSTGRES_USER
               valueFrom:
                 secretKeyRef:
                   name: stateful-todo-secret
                   key: DB_USER
            -  name: POSTGRES_PASSWORD
               valueFrom:
                 secretKeyRef:
                   name: stateful-todo-secret
                   key: DB_PASSWORD
            -  name: POSTGRES_DB
               value: stateful-todo-db
  volumeClaimTemplates:
    - metadata:
        name: postgredb-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 1Gi