# Шлюз Istio
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway   # use istio default ingress gateway
  servers:
    - port:
        number: 80
        name: statedul-todo
        protocol: HTTP
      hosts:
        - "stateful-todo.k3s.dev.com"
    - port:
        number: 80
        name: longhorn
        protocol: HTTP
      hosts:
        - "longhorn.k3s.dev.com"
    - port:
        number: 80
        name: kiali
        protocol: HTTP
      hosts:
        - "kiali.k3s.dev.com"