# проброс 5000 порта из пода на 30000 порт узла кластера k8s
apiVersion: v1
kind: Service
metadata:
  name: stateless-todo-nodeport-service
  namespace: stateless-todo
spec:
  type: NodePort
  selector:
    app: stateless-todo
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
      nodePort: 30000
