apiVersion: apps/v1
kind: Deployment
metadata:
  name: stateless-todo
  namespace: stateless-todo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stateless-todo
  template:
    metadata:
      labels:
        app: stateless-todo
    spec:
      containers:
        - name: stateless-todo
          image: arslanovdi/stateless-todo:v0.0.1
          ports:
            - containerPort: 5000