apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stateful-todo
  namespace: argocd
spec:
  destination:
    namespace: stateful-todo
    server: https://192.168.2.50:6443
  project: default
  source:
    path: ArgoCD/k8s
    repoURL: https://github.com/arslanovdi/k8s_examples
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
