apiVersion: v1
kind: Service
metadata:
  name: stateful-todo-stable #-clusterip-service
  namespace: stateful-todo
spec:
  type: ClusterIP
  selector:
    app: stateful-todo
    version: stable
  ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: 5000