# virtualservice определяем правила маршрутизации
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ template "stateful-todo.fullname" . }}
  namespace: stateful-todo
spec:
  hosts:
    - "stateful-todo.k3s.dev.com"
  gateways:
    - "istio-system/gateway"
  http:
    - match:
        - uri:
            prefix: /tasks
      route:  # канареечное развертывание
        - destination:
            host: {{ template "stateful-todo.fullname" . }}
            port:
              number: 5000