apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "stateful-todo.fullname" . }}
  namespace: stateful-todo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "stateful-todo.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "stateful-todo.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "stateful-todo.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag  }}"
          resources:
            requests:
              memory: "1Mi"
              cpu: "1m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /tasks
              port: 5000
            initialDelaySeconds: 5  # секунд до начала проверки
            periodSeconds: 5        # секунд между проверками
            timeoutSeconds: 3       # секунд ожидания ответа, если превышено то проба неудачная
            successThreshold: 1     # количество последовательных успешных проверок, чтобы подтвердить состояние
            failureThreshold: 3     # количество последовательных неудачных проверок, чтобы считать контейнер мертвым...
            terminationGracePeriodSeconds: 10 # секунд ожидания после получения SIGTERM
          readinessProbe:
            httpGet:
              path: /tasks
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 15
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: user.postgres.credentials.postgresql.acid.zalan.do
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user.postgres.credentials.postgresql.acid.zalan.do
                  key: password
            - name: DB_HOST
              value: "postgres.stateful-todo.svc.cluster.local"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "stateful-todo-db"