# создание namespace
apiVersion: v1
kind: Namespace
metadata:
    name: {{ .Chart.Name }}

---

# Лимиты контейнера в namespace, по умолчанию.
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ template "stateful-todo.fullname" . }}
  namespace: {{ .Chart.Name }}
spec:
  limits:
    - defaultRequest:   # запрос по умолчанию
        memory: "64Mi"
        cpu: "250m"
      default:          # лимит по умолчанию
        memory: "512Mi"
        cpu: "1000m"
      type: Container