apiVersion: v1
kind: Service
metadata:
  name: {{ template "stateful-todo.fullname" . }}
  namespace: stateful-todo
spec:
  type: ClusterIP
  selector:
    app: {{ template "stateful-todo.fullname" . }}
  ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: 5000