name: Go Test, build, push Docker image and release Helm chart
on:
  #release:
  #  types: [published]
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
    jobs:
      unit_tests:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            go-version: [ '1.23.4' ]
        steps:
          - uses: actions/checkout@v4
          - name: Setup Go ${{ matrix.go-version }}
            uses: actions/setup-go@v5
            with:
              go-version: ${{ matrix.go-version }}
          - name: Display Go version
            run: go version
          - name: Build
            run: go build -v ./stateful-todo/cmd/...
          - name: Test with the Go CLI
            run: go test ./stateful-todo/...

      build_and_push_to_docker_hub:
        runs-on: ubuntu-latest
        needs: unit_tests
        permissions:
          packages: write
          contents: read
          attestations: write
          id-token: write
        steps:
          - name: Check out the repo
            uses: actions/checkout@v4

          - name: Log in to Docker Hub
            uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

          - name: Extract metadata (tags, labels) for Docker
            id: meta
            uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
            with:
              images: ${{ vars.DOCKER_HUB_NAMESPACE }}/${{ vars.DOCKER_HUB_REPOSITORY }}

          - name: Build and push Docker image
            id: push
            uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
            with:
              context: .
              file: ./stateful-todo/Dockerfile
              push: true
              tags: ${{ steps.meta.outputs.tags }}
              labels: ${{ steps.meta.outputs.labels }}

          - name: Generate artifact attestation
            uses: actions/attest-build-provenance@v2
            with:
              subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
              subject-digest: ${{ steps.push.outputs.digest }}
              push-to-registry: true
